version: "2"

services:
  yt_postgres:
    image: postgres:15
    container_name: yt_postgres
    volumes:
      - ~/.pg/pg_data/yt:/var/lib/postgresql/data
    env_file:
      - .env
  youtube_project:
    build:
      context: .
      dockerfile: Dockerfile
    image: yt_django:latest
    container_name: yt_django
    depends_on:
      - yt_postgres
    volumes:
      - static_volume:/yt/static
      - media_volume:/yt/media
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOST}
      - LETSENCRYPT_HOST=${ALLOWED_HOST}
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 soaqaz.wsgi:application"
  nginx_proxy:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx_proxy/
    container_name: yt_nginx_proxy
    image: yt_nginx_proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - static_volume:/yt/static
      - media_volume:/yt/media
    depends_on:
      - youtube_project
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "${NGINX_EXTERNAL_SSL_PORT}:80"
  acme_companion:
    image: nginxproxy/acme-companion
    container_name: yt_app_acme_companion
    volumes_from:
      - nginx_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
volumes:
  static_volume:
  media_volume:
  certs:
  vhost:
  html:
  acme:
