version: "2"

services:
  yt_postgres:
    image: postgres:15
    container_name: yt_postgres
    volumes:
      - ~/.pg/pg_data/yt:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "127.0.0.1:15432:5432"
  youtube_project:
    image: registry.soaqa.ru/soaqa/youtube_project
    container_name: yt_django
    depends_on:
      - yt_postgres
    volumes:
      - static_volume:/yt/static
      - media_volume:/yt/media
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOST}
      - LETSENCRYPT_HOST=${ALLOWED_HOST}
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate  && gunicorn -b 0.0.0.0:8000 soaqaz.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: yt_nginx
    image: yt_nginx
    volumes:
      - static_volume:/yt/static
      - media_volume:/yt/media
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - youtube_project
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "${NGINX_EXTERNAL_SSL_PORT}:443"
  acme_companion:
    image: nginxproxy/acme-companion:2.2
    container_name: yt_acme_companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30 yt_django


volumes:
  static_volume:
  media_volume:
  certs:
  vhost:
  html:
  acme:
