version: "3.9"

services:
  db:
    image: postgres:15
    container_name: yt_postgres
    volumes:
      - ~/.pg/pg_data/yt:/var/lib/postgresql/data
    env_file:
      - .env
  yt:
    image: yt_django:latest
    container_name: yt_django
    depends_on:
      - db
    volumes:
      - static_volume:/yt/static
      - media_volume:/yt/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 soaqaz.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: yt_nginx
    image: yt_nginx
    volumes:
      - static_volume:/yt/static
      - media_volume:/yt/media
    depends_on:
      - yt
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"


volumes:
  static_volume:
  media_volume: